[project]
name = "whisper-web"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mutagen>=1.47.0",
    "pydub>=0.25.1",
    "websockets>=15.0.1",
]
